FROM ubuntu:18.04

RUN apt-get update -qq && apt-get install -y \
    git \
    wget \
    build-essential 

# cmake
# https://cmake.org/download/
# https://www.linuxfordevices.com/tutorials/install-cmake-on-linux
RUN mkdir /opt/cmake && \
    cd /tmp && \
    wget https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.sh && \
    sh ./cmake-3.19.2-Linux-x86_64.sh --prefix=/opt/cmake --skip-license && \
    ln -f -s /opt/cmake/bin/cmake /usr/bin/cmake && \
    rm -rf /tmp/cmake-3.19.2-Linux-x86_64.sh

# fmt
WORKDIR /tmp
RUN git clone --recursive https://github.com/fmtlib/fmt.git && \
    cd /tmp/fmt && \
    git checkout 7.1.3 && \
    mkdir -p /tmp/fmt/build && cd /tmp/fmt/build && \
    cmake -DBUILD_SHARED_LIBS=TRUE .. && \
    cmake --build . --target install && \
    rm -rf /tmp/fmt

